const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Flash,
		C3.Behaviors.Pin,
		C3.Plugins.TextBox,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Plugins.Share,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Exps.LayerNumber,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.TextBox.Acts.SetFocus,
		C3.Plugins.TextBox.Acts.SetPlaceholder,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Arr.Acts.SplitString,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Arr.Acts.Shuffle
	];
};
self.C3_JsPropNameTable = [
	{posX: 0},
	{player1: 0},
	{fullScreenBtn: 0},
	{player2: 0},
	{isActive: 0},
	{posY: 0},
	{animationQueue: 0},
	{cardIndex: 0},
	{Tween: 0},
	{Flash: 0},
	{isimKart: 0},
	{Pin: 0},
	{sembolKart: 0},
	{shareBtn: 0},
	{audioBtn: 0},
	{refreshBtn: 0},
	{introBg: 0},
	{gameBtn: 0},
	{popupTextInput: 0},
	{popupTextImage: 0},
	{singlePlayer: 0},
	{multiPlayer: 0},
	{Mouse: 0},
	{Audio: 0},
	{Touch: 0},
	{Browser: 0},
	{player1Text: 0},
	{player2Text: 0},
	{player1ScoreText: 0},
	{player2ScoreText: 0},
	{timeBg: 0},
	{timeText: 0},
	{beh_tween: 0},
	{selectedArea: 0},
	{animationİsimKartQueue: 0},
	{animationSembolKartQueue: 0},
	{isimCardShadow: 0},
	{sembolCardShadow: 0},
	{player1CardAreaBg: 0},
	{closePlayer1Btn: 0},
	{player2CardAreaBg: 0},
	{closePlayer2Btn: 0},
	{Share: 0},
	{oyunarkaplan: 0},
	{choosePlayerBg: 0},
	{buttons: 0},
	{cards: 0},
	{isMultiplayer: 0},
	{player1Control: 0},
	{player2Control: 0},
	{player1NameComplete: 0},
	{player1Name: 0},
	{player2Name: 0},
	{timeCount: 0},
	{isimPosYArtisMiktar: 0},
	{sembolPosYArtisMiktar: 0},
	{cardIndexes: 0},
	{timeStart: 0},
	{isimCardControl: 0},
	{sembolCardControl: 0},
	{isimCardIndex: 0},
	{sembolCardIndex: 0},
	{selectIsimCardUID: 0},
	{selectSembolCardUID: 0},
	{player1Score: 0},
	{player2Score: 0},
	{soundControl: 0},
	{cardX: 0},
	{cardY: 0}
];

self.InstanceType = {
	player1: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	player2: class extends self.ISpriteInstance {},
	isimKart: class extends self.ISpriteInstance {},
	sembolKart: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	introBg: class extends self.ISpriteInstance {},
	gameBtn: class extends self.ISpriteInstance {},
	popupTextInput: class extends self.ITextInputInstance {},
	popupTextImage: class extends self.ISpriteInstance {},
	singlePlayer: class extends self.ISpriteInstance {},
	multiPlayer: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	player1Text: class extends self.ITextInstance {},
	player2Text: class extends self.ITextInstance {},
	player1ScoreText: class extends self.ITextInstance {},
	player2ScoreText: class extends self.ITextInstance {},
	timeBg: class extends self.ISpriteInstance {},
	timeText: class extends self.ITextInstance {},
	selectedArea: class extends self.ISpriteInstance {},
	animationİsimKartQueue: class extends self.IArrayInstance {},
	animationSembolKartQueue: class extends self.IArrayInstance {},
	isimCardShadow: class extends self.ISpriteInstance {},
	sembolCardShadow: class extends self.ISpriteInstance {},
	player1CardAreaBg: class extends self.ISpriteInstance {},
	closePlayer1Btn: class extends self.ISpriteInstance {},
	player2CardAreaBg: class extends self.ISpriteInstance {},
	closePlayer2Btn: class extends self.ISpriteInstance {},
	Share: class extends self.IInstance {},
	oyunarkaplan: class extends self.ISpriteInstance {},
	choosePlayerBg: class extends self.ISpriteInstance {},
	buttons: class extends self.ISpriteInstance {},
	cards: class extends self.ISpriteInstance {}
}